version: '3.8'

services:
  namenode:
    platform: linux/amd64
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=spark-lab
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop

  resourcemanager:
    platform: linux/amd64
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    environment:
      - SERVICE_PRECONDITION=namenode:9000 datanode:9864
    ports:
      - "8088:8088"
    networks:
      - hadoop

  nodemanager:
    platform: linux/amd64
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    environment:
      - SERVICE_PRECONDITION=resourcemanager:8088
    networks:
      - hadoop

  spark:
    image: apache/spark:3.5.0
    container_name: spark-client
    environment:
      - SPARK_MODE=client
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "-lc", "sleep infinity"]
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop: